version: '3'
services:
  internet-banking-server:
    image: huynhducle20000/project-internet-banking
    ports:
      - 3000:3000
    restart: unless-stopped
  internet-banking-ui:
    image: project-internet-banking-front-end
    ports:
      - 5000:80
    restart: unless-stopped